// Write go2rtc.yaml from the live device list, so cameras appear without hand-edited YAML.
//
// The normal <serial> stream carries video, camera audio, and a lazy microphone backchannel. The card
// opens a separate audio-only WebRTC call on this same stream ID, so it never switches away from video.
// Viewing/probing cannot open the speaker: the worker waits for actual microphone samples on stdin.
// The legacy <serial>_2way audio-only stream remains available for clients with a separate call target.
//
// The file contains real serials, so it is gitignored and generated at startup.
import { writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";

// A device that carries live video: a describeDevice() summary with a `stream` path (capabilities
// include camera/video). This matches what HA turns into a camera entity — using deviceClass here
// would miss a camera the SDK downgrades to "other" for sitting behind a HomeBase (not direct P2P).
const isCamera = (d) => Boolean(d.stream);
const hasIncomingAudio = (d) => d.audio?.incoming ?? typeof d.state?.microphone === "boolean";
const hasTalkback = (d) => d.audio?.talkback ?? typeof d.state?.speaker === "boolean";

export async function writeGo2rtcConfig(cfg, devices) {
  const cams = devices.filter(isCamera);
  const lines = [
    "# generated by ha-eufy-sdk-bridge at startup — do not edit (contains real serials)",
    "api:",
    '  listen: ":1984"',
    // HA's authenticated Web Proxy forwards the browser Origin while connecting to this internal
    // host. go2rtc's default same-host check rejects both live and microphone signaling with 403.
    // Keep this API on the private container network; do not publish :1984 to the host.
    '  origin: "*"',
    "rtsp:",
    '  listen: ":8554"',
    "webrtc:",
    '  listen: ":8555"',
    // /audio/<sn> is raw signed 16-bit LE, 16 kHz mono. Tell go2rtc's ffmpeg wrapper exactly how
    // to interpret it, then encode Opus for browser WebRTC.
    "ffmpeg:",
    // Raw PCM already has a known format. Default FFmpeg probing buffers seconds of camera audio,
    // delaying the whole Live negotiation; keep analysis bounded to its first tiny PCM packet.
    '  eufy_pcm: "-probesize 32 -analyzeduration 1 -fflags nobuffer -flags low_delay -f s16le -ar 16000 -ac 1 -i {input}"',
  ];
  // ICE needs the host's published address/port, which can differ from the container listener.
  if (cfg.webrtcCandidates?.length) {
    lines.splice(
      lines.indexOf("ffmpeg:"),
      0,
      "  candidates:",
      ...cfg.webrtcCandidates.map((c) => `    - ${JSON.stringify(c)}`),
    );
  }
  lines.push("streams:");

  for (const d of cams) {
    // go2rtc's native Annex-B producer identifies SPS/VPS immediately and stamps frames from wall
    // clock itself. A cold SDK open must not race FFmpeg's fixed 30-second process launch deadline.
    lines.push(`  ${d.sn}:`);
    lines.push(`    - http://${cfg.selfHost}:${cfg.port}/stream/${d.sn}`);
    if (hasIncomingAudio(d)) {
      lines.push(`    - ffmpeg:http://${cfg.selfHost}:${cfg.port}/audio/${d.sn}#input=eufy_pcm#audio=opus`);
    }

    // go2rtc writes browser microphone PCMA to this process's stdin.
    // The worker does not connect to the bridge/open talkback until stdin contains audio, so metadata probes
    // are harmless and ordinary viewing never occupies the camera speaker.
    if (hasTalkback(d)) {
      const backchannel = `    - exec:node /app/src/talkback-worker.mjs ${d.sn}#backchannel=1#audio=alaw/8000#killsignal=15#killtimeout=5`;
      lines.push(backchannel);
      lines.push(`  ${d.sn}_2way:`);
      lines.push(backchannel);
    }
  }

  const yaml = lines.join("\n") + "\n";
  await mkdir(dirname(cfg.go2rtcConfig), { recursive: true }).catch(() => {});
  await writeFile(cfg.go2rtcConfig, yaml, "utf8");
  return cams.map((d) => d.sn);
}
